server:
  port: 8200
logging:
  file: app.log
spring:  application:    name: child
  boot:    admin:      client:        url:        - http://localhost:9000/
        username: admin
        password: changeit
        instance:          serviceUrl: http://localhost:8200/
management:  endpoints:    web:      exposure:        include: "*"
  endpoint:    health:      showDetails: always
eureka:
  server:
    username: admin
    password: changeit
    hostname: localhost  client:    serviceUrl:      defaultZone: http://${eureka.server.username}:${eureka.server.password}@${eureka.server.hostname}:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:    leaseExpirationDurationInSeconds: 5   