version: "3.6"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    expose:
      - 9200
      - 9300
    networks:
      - elastic-net
    environment:
      discovery.type: single-node
    volumes:
      - type: volume
        source: elasticsearch-data
        target: /var/lib/mysql/
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elastic-net
    depends_on:
      - elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.1
    container_name: logstash
    ports:
      - 5044:5044
      - 9600:9600
    expose:
      - 5044
      - 9600
    networks:
      - elastic-net
    volumes:
      - type: bind
        source: ./logstash.conf
        target: /usr/share/logstash/logstash.conf
    command: logstash -f /usr/share/logstash/logstash.conf
    depends_on:
      - elasticsearch
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.6.1
    container_name: filebeat
    networks:
      - elastic-net
    volumes:
      - type: bind
        source: ./filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
      - type: bind
        source: ./../../MicroserviceInstance1/app.log
        target: /usr/share/filebeat/logs/microservice1/app.log
      - type: bind
        source: ./../../MicroserviceInstance2/app.log
        target: /usr/share/filebeat/logs/microservice2/app.log
      - type: bind
        source: ./../../MicroserviceInstance3/app.log
        target: /usr/share/filebeat/logs/microservice3/app.log
      - type: bind
        source: ./../../MicroserviceZuulGateway/app.log
        target: /usr/share/filebeat/logs/microservice-zuul/app.log                
      - type: bind
        source: ./../../MicroserviceOAuth2Server/app.log
        target: /usr/share/filebeat/logs/microservice-oauth2-server/app.log          
    command: filebeat -c /usr/share/filebeat/filebeat.yml
    depends_on:
      - logstash
networks:
  elastic-net:
    driver: bridge
volumes:
  elasticsearch-data:
  