spring:
  application:
    name: service-registry
server:  port: 8761
eureka:  client:
    register-with-eureka: false
    fetch-registry: false
admin:
  username: "admin"
  password: "changeit"
  role: "ADMIN"