logging:
  file: app.log
server:
  port: 8000
spring:  application:    name: authorization-server
  boot:    admin:      client:        url:        - http://localhost:9000/
        username: admin
        password: changeit
        instance:          serviceUrl: http://localhost:8000/
  redis:
    host: localhost
    port: 6379
    password: changeit
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: changeit
  jpa:
    hibernate:
      ddl-auto: update
management:  endpoints:    web:      exposure:        include: "*"
  endpoint:    health:      showDetails: always
eureka:
  server:
    username: admin
    password: changeit
    hostname: localhost  client:    serviceUrl:       defaultZone: http://${eureka.server.username}:${eureka.server.password}@${eureka.server.hostname}:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true 
    ipAddress: 127.0.0.1 
    hostname: localhost
jwt:
  keyStore: classpath:jwt.p12
  keyStorePassword: changeit
  keyAlias: jwt
  keyPairPassword: changeit
admin:
  user:
    username: admin
    password: changeit
    email: admin@admin.com
    role: ADMIN
  client:
    clientId: admin
    clientSecret: changeit
    authority: ADMIN