version: "3.6"
services:
  mysql:
    image: "mysql:5"
    container_name: "mysql"
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "changeit"
    volumes:
      - type: volume
        source: mysqldb
        target: /var/lib/mysql/
  redis:
    image: "redis:5"
    container_name: "redis"
    ports:
      - 6379:6379
    expose:
      - 6379
    command: redis-server --requirepass changeit
volumes:
  mysqldb: